### PR TITLE
Portuguese (pt_PT) update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by Viper007Bond** [comment]
Hi! Thanks for this but my plugin is actually moving towards using language packs which means that rather than having to bundle a bunch of translations with the plugin itself, they're automatically downloaded from WordPress.org as needed.

That means that translations are now done using GlotPress on WordPress.org. You can find my plugin here:

https://translate.wordpress.org/projects/wp-plugins/regenerate-thumbnails

If you need help, there's this great guide here:

https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/

Your previous translations should have already been imported and then once I finish work on this major rewrite, the new strings will show up there for translation. :)

**Comment by pedro-mendonca** [comment]
Great, that's simpler than.
I've already pushed there the current translation, but not this last strings, I'll keep an eye there and complete it once you'll add the rest of the strings.
Thanks.

**Comment by Viper007Bond** [comment]
No, thank you! :)

**Comment by Viper007Bond** [comment]
If you give me your WordPress.org username, I can request for you to be added as [a translation editor](https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/) for Portuguese for my plugin if you want.

**Comment by pedro-mendonca** [comment]
Thanks, I think I am already, as I've been pushing it's translation there as well.

**Comment by Viper007Bond** [comment]
Anyone can contribute translations however only editors can approve them and make them go live to users. But maybe you are due to other translation work? I dunno.

**Pull request closed without merging**
