### PR TITLE
Bulk processing and image size options

### PR DESCRIPTION
**Pull request by mboynes**
# Bulk processing and size options.
## Bulk Processing

For sites with large numbers of images (100k+), processing images one at a time can take days, even for a powerful server, when the requests go through one at a time due to the time/cost-per-request. By adding an option for how many images to process at a time, the user has the ability to control the balance between memory limits and cost-per-request.
## Size Options

You can now choose which sizes you want regenerated when rebuilding images for your entire site, instead of being forced to do every image size.

### CODE REVIEW

**Comment by Viper007Bond** [comment]
For bulk processing, I'm planning on adding a [wp-cli](http://wp-cli.org/) command that will be bundled with this plugin. If you're regenerating that many images, it's probably best to do it via the command line rather than a browser.

For the sizes, if I'm reading it correctly, you're playing around with what image sizes are registered so that it only regenerates the sizes you want. However won't that have bad consequences when `wp_update_attachment_metadata()` is called because only the sizes you just generated will be registered as existing? WordPress looks to this metadata to know what thumbnail sizes exist when supplying a thumbnail URL.

**Comment by mboynes** [comment]
Good call on the metadata. Fix coming forward.

Re:bulk processing, this still makes it faster even if you have a few hundred images. For me, processing 100 at a time is about 400% faster; it also reduces bandwidth and POST requests, both of which a user may pay for if htey're using cloud hosting. Food for thought.

**Comment by Viper007Bond** [comment]
I was processing one at a time for memory reasons since the whole image has to be loaded into memory to work. I like this idea of being able to increase it though if the user wants and knows the have extra memory to work with (or small images).

I'll take a look at the code soon.

**Comment by mboynes** [comment]
Also note that I hid the success messages and am only displaying the error messages. This makes them more relevant and easy to see, and it stops the browser from getting wonky when there's 100,000 nodes in that list. Just want to make sure you don't miss that I did that.

**Comment by Viper007Bond** [comment]
Yeah, that's also on my todo list. Browsers start choking when you regenerate tons of images. I was planning on adding a debug checkbox that would toggle that.

I may tweak your code a bit and not use it verbatim but this is certainly a big help and appreciated. Thanks.

**Comment by mikelberry** [comment]
It'd be handy if the "currently resizing ID" were more prominent, along with adding an offset field in the UI for bulk processing for users that don't have the option of using WP CLI.

The issue is that should bulk processing fail (the process freezes or someone closes the browser window), you need to start over, thus regenerating thumbnails for images that have already been processed.

**Comment by Viper007Bond** [comment]
Bulk processing was added to WP-CLI quite a while back and is the best way to resize a large number of images. You can just run it in a `screen` and it'll finish itself up.

I'm going to close this as `wontfix`. This plugin is meant for a more reasonable number of media items.

**Pull request closed without merging**
